print("나만의 프롬프트 관리 프로그램")
print("1. 프롬프트 추가")
print("2. 전체 목록 보기")
print("3. 카테고리별 보기")
print("4. 프롬프트 검색")
print("5. 상세 보기")
print("6. 즐겨찾기 관리")
print("0. 종료")
choice = input("메뉴를 선택하세요: ")
print("선택한 메뉴:", choice)